name: Deploy real-world to AWS EC2

on:
  push:
    branches:
      - main # khi có code đc merge (push) vào nhánh main thì chạy job

jobs:
  deploy: # đặt tên tùy thích
    runs-on: ubuntu-22.04 # phiên bản ubuntu

    steps: # build trc trên git để xem có lỗi ko trc khi đưa lên server
    - name: Checkout code
      uses: actions/checkout@v3 # đây là bước lấy code nhánh main về 

    - name: Set up Node.js
      uses: actions/setup-node@v3 # cài đặt môi trường build trên git (nodejs)
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install # cái package cần thiết

    - name: Build project
      run: npm run build # build project

    - name: Deploy to AWS EC2 # vẫn đang chạy trên máy ảo của github, "ubuntu" là tên username của EC2, "mkdir -p" -p là nếu có thư mục rồi thì ko tạo nữa
      env:
        # SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} // doesn't work
        ENV_FILE: ${{ secrets.ENV_FILE }}
        # EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }} // doesn't work
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -tt -o StrictHostKeyChecking=no -p 22 ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << EOF
          pm2 stop all --no-daemon
          rm -rf ~/real-world
          git clone git@github.com:dtvthethe/real-world.git
          cd ~/real-world
          echo "$ENV_FILE" > .env
          git pull origin main
          npm install --silent
          npm run build
          pm2 restart all --no-daemon
          exit
        EOF
        exit
